/**
 * Use-cases voor 'report:generate-ohm' en 'report:generate-diepte'.
 *
 * Kern van bevinding B2: de oude `/api/pdf/route.ts` nam `results` en
 * `inputValues` letterlijk van de client aan en rendered ze ongezien in een
 * "officieel" ogend PDF. Hier is dat structureel onmogelijk gemaakt:
 *  - Ohm: het resultaat wordt ALTIJD server-side herberekend met
 *    `calcOhmWizard()` (de canonieke bron per docs/contracts.md §A) uit
 *    gevalideerde primitieve invoer. Er is geen "results"-veld in het
 *    inputschema van deze use-case — het bestaat simpelweg niet als optie.
 *  - Diepte: het resultaat komt ALTIJD uit de server-side opgeslagen
 *    `calculations`-rij (lib/domain/calculation-repository.ts), pas nadat
 *    de authz-kernel heeft bevestigd dat de aanroeper de eigenaar is. De
 *    client levert alleen een ID, nooit de inhoud.
 */

import { z } from 'zod';
import React from 'react';
import { renderToBuffer } from '@react-pdf/renderer';
import { createClient } from '@/utils/supabase/server';
import { cookies } from 'next/headers';
import { calcOhmWizard, type OhmWizardInput } from '@/lib/calculations';
import { getOwnedCalculation } from '@/lib/domain/calculation-repository';
import { renderStoredCalculationPdf } from '@/lib/domain/report-rendering';
import { ReportTemplate } from '@/components/pdf/ReportTemplate';
import type { AuthorizedContext } from '@/lib/authz/context';

// ─── Ohm — server-side herberekend, geen opgeslagen resultaat nodig ────────────

export const OhmReportInput = z.object({
  tool: z.literal('ohm'),
  locale: z.enum(['nl', 'en', 'de']).default('nl'),
  customerType: z.enum(['particulier', 'zakelijk']),
  installationType: z.enum(['woning', 'utiliteit', 'industrieel', 'bliksem', 'medisch']),
  gridSystem: z.enum(['TT', 'TN', 'IT']).optional(),
  rcdPresent: z.boolean().optional(),
  rcdCurrent: z.number().positive().optional(),
  breakerType: z.enum(['B', 'C', 'D']).optional(),
  breakerAmps: z.number().positive().optional(),
  voltageLimit: z.union([z.literal(25), z.literal(50)]).optional(),
});

export type OhmReportInput = z.infer<typeof OhmReportInput>;

const OHM_EXPLANATION: Record<'nl' | 'en' | 'de', string> = {
  nl: 'De aardingsweerstand is berekend conform NEN 1010. De maximale aardingsweerstand volgt uit Ra ≤ UL/IΔn.',
  en: 'The grounding resistance was calculated in accordance with NEN 1010. The maximum resistance follows from Ra ≤ UL/IΔn.',
  de: 'Der Erdungswiderstand wurde gemäß NEN 1010 berechnet. Der maximale Widerstand ergibt sich aus Ra ≤ UL/IΔn.',
};

export interface ReportOutcome {
  pdfBuffer: Buffer;
  /** Alleen gezet als de PDF is opgeslagen (ingelogde gebruiker) — anders krijgt de client de bytes direct. */
  pdfUrl: string | null;
}

export async function generateOhmReport(
  ctx: AuthorizedContext<'report:generate-ohm'>,
  input: OhmReportInput,
): Promise<ReportOutcome> {
  const wizardInput: OhmWizardInput = {
    customerType: input.customerType,
    installationType: input.installationType,
    gridSystem: input.gridSystem,
    rcdPresent: input.rcdPresent,
    rcdCurrent: input.rcdCurrent,
    breakerType: input.breakerType,
    breakerAmps: input.breakerAmps,
    voltageLimit: input.voltageLimit,
  };
  const result = calcOhmWizard(wizardInput); // server-side, canoniek — nooit client-input

  // ReportTemplate toont alleen string/number — booleans/undefined worden
  // hier expliciet naar weergavewaarden vertaald (geen `as`-cast op het hele
  // object, dat zou stil een verkeerd type kunnen doorlaten).
  const displayInputValues: Record<string, string | number> = {
    customerType: wizardInput.customerType,
    installationType: wizardInput.installationType,
    ...(wizardInput.gridSystem ? { gridSystem: wizardInput.gridSystem } : {}),
    ...(wizardInput.rcdPresent != null ? { rcdPresent: wizardInput.rcdPresent ? 'ja' : 'nee' } : {}),
    ...(wizardInput.rcdCurrent != null ? { rcdCurrent: wizardInput.rcdCurrent } : {}),
    ...(wizardInput.breakerType ? { breakerType: wizardInput.breakerType } : {}),
    ...(wizardInput.breakerAmps != null ? { breakerAmps: wizardInput.breakerAmps } : {}),
    ...(wizardInput.voltageLimit != null ? { voltageLimit: wizardInput.voltageLimit } : {}),
  };

  const element = React.createElement(ReportTemplate, {
    tool: 'ohm',
    inputValues: displayInputValues,
    results: {
      maxResistance: `${result.maxResistance.toFixed(1)} Ω`,
      indication: result.indication,
      norm: result.norm,
    },
    explanationText: OHM_EXPLANATION[input.locale],
    reportTitle: input.locale === 'nl' ? 'Aardingsrapport' : 'Grounding Report',
    generatedByText: input.locale === 'nl' ? 'Gegenereerd door EarthGND' : 'Generated by EarthGND',
    inputValuesLabel: input.locale === 'nl' ? 'Invoerwaarden' : 'Input values',
    resultsLabel: input.locale === 'nl' ? 'Resultaten' : 'Results',
    explanationLabel: input.locale === 'nl' ? 'Toelichting' : 'Explanation',
    dateLabel: input.locale === 'nl' ? 'Datum' : 'Date',
  });

  const pdfBuffer = (await renderToBuffer(element as Parameters<typeof renderToBuffer>[0])) as Buffer;

  // Alleen opslaan als de aanroeper ingelogd is — anonieme Ohm-gebruikers
  // krijgen de bytes direct terug, exact zoals vóór deze migratie.
  if (ctx.principal.kind !== 'user') {
    return { pdfBuffer, pdfUrl: null };
  }

  const supabase = createClient(await cookies());
  const fileName = `${ctx.principal.id}/${Date.now()}-ohm-report.pdf`;
  const { error: uploadError } = await supabase.storage
    .from('reports')
    .upload(fileName, pdfBuffer, { contentType: 'application/pdf', upsert: false });

  if (uploadError) return { pdfBuffer, pdfUrl: null };

  const { data: signed } = await supabase.storage.from('reports').createSignedUrl(fileName, 60 * 60 * 24 * 7);
  const pdfUrl = signed?.signedUrl ?? null;

  await supabase.from('calculations').insert({
    user_id: ctx.principal.id,
    tool: 'ohm',
    input_values: wizardInput,
    result: { maxResistance: result.maxResistance, indication: result.indication, norm: result.norm },
    pdf_url: pdfUrl,
  });

  return { pdfBuffer, pdfUrl };
}

// ─── Diepte — uitsluitend uit de opgeslagen, al-betaalde calculation-rij ───────

export const DiepteReportInput = z.object({
  tool: z.literal('diepte'),
  calculationId: z.string().uuid(),
  locale: z.enum(['nl', 'en', 'de']).default('nl'),
});

export type DiepteReportInput = z.infer<typeof DiepteReportInput>;

/** resourceOwner voor defineEndpoint — server-side lookup, nooit de client geloven. */
export async function findDiepteCalculationOwner(input: DiepteReportInput): Promise<string | null> {
  const { findCalculationOwnerId } = await import('@/lib/domain/calculation-repository');
  const supabase = createClient(await cookies());
  return findCalculationOwnerId(supabase, input.calculationId);
}

export async function generateDiepteReport(
  ctx: AuthorizedContext<'report:generate-diepte'>,
  input: DiepteReportInput,
): Promise<ReportOutcome> {
  // Runtime-garantie van de registry ('report:generate-diepte' staat alleen
  // 'user' toe) herhaald als lokale type guard, zodat TypeScript `.id` hier
  // toestaat zonder de bredere Principal-union open te breken.
  if (ctx.principal.kind !== 'user') throw new Error('Onverwacht principal-type voor report:generate-diepte');

  const supabase = createClient(await cookies());
  const calc = await getOwnedCalculation(supabase, input.calculationId, ctx.principal.id);
  if (!calc) {
    // Kan hier alleen gebeuren bij een race tussen resourceOwner-lookup en
    // deze tweede, verdedigende lookup (bv. de rij is net verwijderd) — nooit
    // doordat de client een ander ID probeerde: dat blokkeert al bij authorize().
    throw new Error('Berekening niet gevonden');
  }

  const pdfBuffer = await renderStoredCalculationPdf(calc, input.locale);

  const fileName = `${ctx.principal.id}/${Date.now()}-diepte-report-${calc.id}.pdf`;
  const { error: uploadError } = await supabase.storage
    .from('reports')
    .upload(fileName, pdfBuffer, { contentType: 'application/pdf', upsert: true });

  if (uploadError) return { pdfBuffer, pdfUrl: null };

  const { data: signed } = await supabase.storage.from('reports').createSignedUrl(fileName, 60 * 60 * 24 * 7);
  const pdfUrl = signed?.signedUrl ?? null;

  if (pdfUrl) {
    await supabase.from('calculations').update({ pdf_url: pdfUrl }).eq('id', calc.id).eq('user_id', ctx.principal.id);
  }

  return { pdfBuffer, pdfUrl };
}
