/**
 * Eén plek die een opgeslagen `calculations`-rij naar een PDF-buffer
 * rendert. Gedeeld door 'report:generate-diepte' (lib/application/
 * report-generate.ts) en 'report:email' (lib/application/report-email.ts) —
 * beide use-cases mogen alleen uit een reeds-eigendomsgecontroleerde rij
 * renderen, nooit uit client-input, dus dit is de enige plaats waar die
 * vertaalslag gebeurt.
 */

import React from 'react';
import { renderToBuffer } from '@react-pdf/renderer';
import { ReportTemplate } from '@/components/pdf/ReportTemplate';
import type { StoredCalculation } from './calculation-repository';

export type ReportLocale = 'nl' | 'en' | 'de';

const EXPLANATION: Record<'ohm' | 'diepte', Record<ReportLocale, string>> = {
  ohm: {
    nl: 'De aardingsweerstand is berekend conform NEN 1010. De maximale aardingsweerstand volgt uit Ra ≤ UL/IΔn.',
    en: 'The grounding resistance was calculated in accordance with NEN 1010. The maximum resistance follows from Ra ≤ UL/IΔn.',
    de: 'Der Erdungswiderstand wurde gemäß NEN 1010 berechnet. Der maximale Widerstand ergibt sich aus Ra ≤ UL/IΔn.',
  },
  diepte: {
    nl: 'De benodigde indraaidiepte is berekend met de formule van Dwight. Meet altijd ter plaatse na installatie conform NEN 3140.',
    en: "The required installation depth is calculated using Dwight's formula. Always measure on-site after installation (NEN 3140).",
    de: 'Die erforderliche Einschlagtiefe wurde nach der Dwight-Formel berechnet. Nach der Installation immer vor Ort messen (NEN 3140).',
  },
};

const LABELS: Record<ReportLocale, { title: string; generatedBy: string; inputValues: string; results: string; explanation: string; date: string }> = {
  nl: { title: 'Aardingsrapport', generatedBy: 'Gegenereerd door EarthGND', inputValues: 'Invoerwaarden', results: 'Resultaten', explanation: 'Toelichting', date: 'Datum' },
  en: { title: 'Grounding Report', generatedBy: 'Generated by EarthGND', inputValues: 'Input values', results: 'Results', explanation: 'Explanation', date: 'Date' },
  de: { title: 'Erdungsbericht', generatedBy: 'Erstellt von EarthGND', inputValues: 'Eingabewerte', results: 'Ergebnisse', explanation: 'Erläuterung', date: 'Datum' },
};

/** Rendert een reeds server-side opgeslagen en eigendomsgecontroleerde rij — nooit client-input. */
export async function renderStoredCalculationPdf(
  calc: Pick<StoredCalculation, 'tool' | 'input_values' | 'result'>,
  locale: ReportLocale,
): Promise<Buffer> {
  const l = LABELS[locale];
  const element = React.createElement(ReportTemplate, {
    tool: calc.tool,
    inputValues: calc.input_values as Record<string, string | number>,
    results: calc.result as Record<string, string | number>,
    explanationText: EXPLANATION[calc.tool][locale],
    reportTitle: l.title,
    generatedByText: l.generatedBy,
    inputValuesLabel: l.inputValues,
    resultsLabel: l.results,
    explanationLabel: l.explanation,
    dateLabel: l.date,
  });
  return (await renderToBuffer(element as Parameters<typeof renderToBuffer>[0])) as Buffer;
}
