import { NextRequest, NextResponse } from 'next/server';
import React from 'react';
import { cookies } from 'next/headers';
import { createClient } from '@/utils/supabase/server';

export const runtime = 'nodejs';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      tool,
      inputValues,
      results,
      warning,
      locale = 'nl',
    } = body as {
      tool: 'ohm' | 'diepte';
      inputValues: Record<string, string | number>;
      results: Record<string, string | number>;
      warning?: string;
      locale?: string;
    };

    const isNl = locale === 'nl';

    // Dynamic import to avoid Edge Runtime issues
    const { renderToBuffer } = await import('@react-pdf/renderer');
    const { ReportTemplate } = await import('@/components/pdf/ReportTemplate');

    const element = React.createElement(ReportTemplate, {
      tool,
      inputValues,
      results,
      warning,
      explanationText: isNl
        ? tool === 'ohm'
          ? 'De aardingsweerstand is berekend conform NEN 1010. De maximale aardingsweerstand volgt uit Ra ≤ UL/IΔn (bv. 1667 Ω bij 30 mA, 167 Ω bij 300 mA). De aanbevolen weerstand is ≤ 30 Ω.'
          : 'De benodigde indraaidiepte is berekend met de formule van Dwight, rekening houdend met de soortelijke weerstand van de bodem, de grondwaterstand en de pH-waarde.'
        : tool === 'ohm'
        ? 'The grounding resistance was calculated in accordance with NEN 1010. The maximum resistance follows from Ra ≤ UL/IΔn (e.g. 1667 Ω for 30 mA, 167 Ω for 300 mA). The recommended resistance is ≤ 30 Ω.'
        : "The required installation depth is calculated using Dwight's formula, taking into account the soil resistivity, groundwater level and pH value.",
      reportTitle: isNl ? 'Aardingsrapport' : 'Grounding Report',
      generatedByText: isNl ? 'Gegenereerd door EarthGND' : 'Generated by EarthGND',
      inputValuesLabel: isNl ? 'Invoerwaarden' : 'Input values',
      resultsLabel: isNl ? 'Resultaten' : 'Results',
      explanationLabel: isNl ? 'Toelichting' : 'Explanation',
      dateLabel: isNl ? 'Datum' : 'Date',
    });

    const pdfBuffer: Buffer = await renderToBuffer(element as Parameters<typeof renderToBuffer>[0]);

    // Store in Supabase Storage if user is authenticated
    const cookieStore = await cookies();
    const supabase = createClient(cookieStore);
    const { data: { user } } = await supabase.auth.getUser();

    let pdfUrl: string | null = null;

    if (user) {
      const fileName = `${user.id}/${Date.now()}-${tool}-report.pdf`;
      const { error: uploadError } = await supabase.storage
        .from('reports')
        .upload(fileName, pdfBuffer, {
          contentType: 'application/pdf',
          upsert: false,
        });

      if (!uploadError) {
        const { data: signedData } = await supabase.storage
          .from('reports')
          .createSignedUrl(fileName, 60 * 60 * 24 * 7);
        pdfUrl = signedData?.signedUrl ?? null;

        await supabase.from('calculations').insert({
          user_id: user.id,
          tool,
          input_values: inputValues,
          result: results,
          pdf_url: pdfUrl,
        });
      }
    }

    if (pdfUrl) {
      return NextResponse.json({ pdfUrl });
    }

    // Return PDF bytes directly when not logged in
    return new NextResponse(pdfBuffer as unknown as BodyInit, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${tool}-report.pdf"`,
      },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
