import { NextRequest, NextResponse } from 'next/server';
import React from 'react';
import { cookies } from 'next/headers';
import { Resend } from 'resend';
import { createClient } from '@/utils/supabase/server';
import type { DiepteRapportProps } from '@/components/pdf/DiepteRapportTemplate';

export const runtime = 'nodejs';

export async function POST(request: NextRequest) {
  if (!process.env.RESEND_API_KEY) {
    return NextResponse.json({ error: 'E-mail niet geconfigureerd op deze server' }, { status: 503 });
  }
  const resend = new Resend(process.env.RESEND_API_KEY);

  try {
    const cookieStore = await cookies();
    const supabase = createClient(cookieStore);
    const { data: { user } } = await supabase.auth.getUser();

    if (!user?.email) {
      return NextResponse.json({ error: 'Niet ingelogd' }, { status: 401 });
    }

    const body = await request.json();
    const {
      tool,
      inputValues,
      results,
      warning,
      locale = 'nl',
      diepteCalcResult,
    } = body as {
      tool: 'ohm' | 'diepte';
      inputValues: Record<string, string | number>;
      results: Record<string, string | number>;
      warning?: string;
      locale?: string;
      diepteCalcResult?: DiepteRapportProps;
    };

    const isNl = locale === 'nl';
    const toolLabel = tool === 'ohm'
      ? (isNl ? 'Weerstand Calculator' : 'Resistance Calculator')
      : (isNl ? 'Pendiepte Calculator' : 'Rod Depth Calculator');

    const { renderToBuffer } = await import('@react-pdf/renderer');

    let pdfBuffer: Buffer;

    // Use the rich Diepte template when full calc result is available
    if (tool === 'diepte' && diepteCalcResult) {
      const { DiepteRapportTemplate } = await import('@/components/pdf/DiepteRapportTemplate');
      const element = React.createElement(DiepteRapportTemplate, diepteCalcResult);
      pdfBuffer = await renderToBuffer(element as Parameters<typeof renderToBuffer>[0]);
    } else {
      // Fallback: generic template (ohm tool, or diepte without full data)
      const { ReportTemplate } = await import('@/components/pdf/ReportTemplate');
      const explanationText = isNl
        ? tool === 'ohm'
          ? 'De aardingsweerstand is berekend conform NEN 1010. De maximale aardingsweerstand volgt uit Ra ≤ UL/IΔn (bv. 1667 Ω bij 30 mA, 167 Ω bij 300 mA). De aanbevolen weerstand is ≤ 30 Ω.'
          : 'De benodigde indraaidiepte is berekend met de formule van Dwight, rekening houdend met de soortelijke weerstand van de bodem, de grondwaterstand en de pH-waarde. Meet altijd ter plaatse na installatie conform NEN 3140.'
        : tool === 'ohm'
          ? 'The grounding resistance was calculated in accordance with NEN 1010. The maximum resistance follows from Ra ≤ UL/IΔn (e.g. 1667 Ω for 30 mA, 167 Ω for 300 mA). The recommended resistance is ≤ 30 Ω.'
          : "The required installation depth is calculated using Dwight's formula, taking into account the soil resistivity, groundwater level and pH. Always measure on-site after installation (NEN 3140).";
      const element = React.createElement(ReportTemplate, {
        tool,
        inputValues,
        results,
        warning,
        explanationText,
        reportTitle: isNl ? 'Aardingsrapport' : 'Grounding Report',
        generatedByText: isNl ? 'Gegenereerd door EarthGND' : 'Generated by EarthGND',
        inputValuesLabel: isNl ? 'Invoerwaarden' : 'Input values',
        resultsLabel: isNl ? 'Resultaten' : 'Results',
        explanationLabel: isNl ? 'Toelichting' : 'Explanation',
        dateLabel: isNl ? 'Datum' : 'Date',
      });
      pdfBuffer = await renderToBuffer(element as Parameters<typeof renderToBuffer>[0]);
    }

    const dateStr = new Date().toLocaleDateString('nl-NL');
    const subject = isNl
      ? `Uw EarthGND rapport — ${toolLabel}`
      : `Your EarthGND report — ${toolLabel}`;

    // Build email body summary — richer for diepte with full data
    let resultRows: string;
    if (tool === 'diepte' && diepteCalcResult) {
      const { scenarios, parallelAdvice, riskClass, corrosionClass } = diepteCalcResult;
      const scenG = scenarios.gunstig;
      const scenM = scenarios.gemiddeld;
      const scenO = scenarios.ongunstig;
      const dimG = 'depth' in scenG ? scenG.depth : scenG.length;
      const dimM = 'depth' in scenM ? scenM.depth : scenM.length;
      const dimO = 'depth' in scenO ? scenO.depth : scenO.length;
      const unit = diepteCalcResult.electrodeType === 'lint' ? 'm lint' : 'm';
      const rows: [string, string][] = [
        ['Bodemweerstand ρ',          `${diepteCalcResult.rho} Ω·m`],
        ['GHG grondwaterstand',       `${diepteCalcResult.groundwaterDepth} m`],
        ['Doelweerstand',             `≤ ${diepteCalcResult.targetResistance} Ω`],
        ['Gunstig scenario',          `${dimG.toFixed(2)} ${unit} · ${scenG.achievedResistance.toFixed(2)} Ω`],
        ['Gemiddeld scenario',        `${dimM.toFixed(2)} ${unit} · ${scenM.achievedResistance.toFixed(2)} Ω`],
        ['Ongunstig scenario',        `${dimO.toFixed(2)} ${unit} · ${scenO.achievedResistance.toFixed(2)} Ω`],
        ...(parallelAdvice ? [
          [`Parallelschakeling`, `${parallelAdvice.aantalPennen} pennen · Ra = ${parallelAdvice.rParallel} Ω`] as [string, string],
        ] : []),
        ['Risicoklasse',              riskClass.label],
        ['Corrosieclassificatie',     corrosionClass.label],
      ];
      resultRows = rows
        .map(([k, v]) => `<tr><td style="padding:4px 12px 4px 0;color:#666;font-size:13px;">${k}</td><td style="padding:4px 0;font-weight:600;font-size:13px;">${v}</td></tr>`)
        .join('');
    } else {
      resultRows = Object.entries(results)
        .map(([k, v]) => `<tr><td style="padding:4px 12px 4px 0;color:#666;">${k}</td><td style="padding:4px 0;font-weight:600;">${v}</td></tr>`)
        .join('');
    }

    const html = `<!DOCTYPE html>
<html lang="nl">
<head><meta charset="UTF-8"></head>
<body style="font-family:sans-serif;background:#f9f9f9;margin:0;padding:24px;">
  <div style="max-width:580px;margin:0 auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);">
    <div style="background:#1C1917;padding:24px 28px;">
      <div style="color:#E8761A;font-size:20px;font-weight:700;">EarthGND</div>
      <div style="color:#F5EFE6;font-size:13px;margin-top:4px;">${toolLabel} — ${dateStr}</div>
    </div>
    <div style="padding:24px 28px;">
      <p style="margin:0 0 16px;color:#333;font-size:14px;">Goedemiddag,</p>
      <p style="margin:0 0 20px;color:#555;line-height:1.6;font-size:13px;">
        In de bijlage vindt u het volledige aardingsrapport als PDF. Hieronder een samenvatting.
      </p>
      <table style="width:100%;border-collapse:collapse;margin-bottom:20px;">
        ${resultRows}
      </table>
      ${warning ? `<p style="background:#fff3cd;border:1px solid #ffc107;padding:10px 14px;border-radius:4px;font-size:12px;color:#856404;margin-bottom:20px;">⚠ ${warning}</p>` : ''}
      <p style="font-size:11px;color:#888;border-top:1px solid #eee;padding-top:16px;margin:0;line-height:1.6;">
        Dit rapport is indicatief op basis van BRO-bodemdata en desktopmodellering.<br>
        Meet altijd ter plaatse na installatie conform NEN 3140 / NEN 1010.<br>
        <a href="https://earthgnd.com" style="color:#E8761A;">earthgnd.com</a>
      </p>
    </div>
  </div>
</body>
</html>`;

    const { error: sendError } = await resend.emails.send({
      from: process.env.RESEND_FROM_EMAIL ?? 'EarthGND <noreply@earthgnd.com>',
      to: user.email,
      subject,
      html,
      attachments: [
        {
          filename: `earthgnd-${tool}-rapport.pdf`,
          content: pdfBuffer.toString('base64'),
        },
      ],
    });

    if (sendError) {
      return NextResponse.json({ error: sendError.message }, { status: 500 });
    }

    return NextResponse.json({ success: true });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

