import { NextRequest, NextResponse } from 'next/server';
import React from 'react';
import { cookies } from 'next/headers';
import { Resend } from 'resend';
import { createClient } from '@/utils/supabase/server';

export const runtime = 'nodejs';

const resend = new Resend(process.env.RESEND_API_KEY ?? 'placeholder');

export async function POST(request: NextRequest) {
  try {
    const cookieStore = await cookies();
    const supabase = createClient(cookieStore);
    const { data: { user } } = await supabase.auth.getUser();

    if (!user?.email) {
      return NextResponse.json({ error: 'Niet ingelogd' }, { status: 401 });
    }

    const body = await request.json();
    const {
      tool,
      inputValues,
      results,
      warning,
      locale = 'nl',
    } = body as {
      tool: 'ohm' | 'diepte';
      inputValues: Record<string, string | number>;
      results: Record<string, string | number>;
      warning?: string;
      locale?: string;
    };

    const isNl = locale === 'nl';
    const toolLabel = tool === 'ohm'
      ? (isNl ? 'Weerstand Calculator' : 'Resistance Calculator')
      : (isNl ? 'Pendiepte Calculator' : 'Rod Depth Calculator');

    const explanationText = isNl
      ? tool === 'ohm'
        ? 'De aardingsweerstand is berekend conform NEN 1010. De theoretische weerstand is gebaseerd op de spanning gedeeld door de maximale lekstroom. De praktische weerstand is beperkt tot 166 Ω en de aanbevolen weerstand tot 30 Ω.'
        : 'De benodigde indraaidiepte is berekend met de formule van Dwight, rekening houdend met de soortelijke weerstand van de bodem, de grondwaterstand en de pH-waarde. Meet altijd ter plaatse na installatie conform NEN 3140.'
      : tool === 'ohm'
        ? 'The grounding resistance was calculated in accordance with NEN 1010. The practical resistance is limited to 166 Ω and the recommended resistance to 30 Ω.'
        : "The required installation depth is calculated using Dwight's formula, taking into account the soil resistivity, groundwater level and pH. Always measure on-site after installation (NEN 3140).";

    // Generate PDF
    const { renderToBuffer } = await import('@react-pdf/renderer');
    const { ReportTemplate } = await import('@/components/pdf/ReportTemplate');

    const element = React.createElement(ReportTemplate, {
      tool,
      inputValues,
      results,
      warning,
      explanationText,
      reportTitle: isNl ? 'Aardingsrapport' : 'Grounding Report',
      generatedByText: isNl ? 'Gegenereerd door EarthGND' : 'Generated by EarthGND',
      inputValuesLabel: isNl ? 'Invoerwaarden' : 'Input values',
      resultsLabel: isNl ? 'Resultaten' : 'Results',
      explanationLabel: isNl ? 'Toelichting' : 'Explanation',
      dateLabel: isNl ? 'Datum' : 'Date',
    });

    const pdfBuffer: Buffer = await renderToBuffer(
      element as Parameters<typeof renderToBuffer>[0],
    );

    const dateStr = new Date().toLocaleDateString('nl-NL');
    const subject = isNl
      ? `Uw EarthGND rapport — ${toolLabel}`
      : `Your EarthGND report — ${toolLabel}`;

    // Build a simple result summary for the email body
    const resultRows = Object.entries(results)
      .map(([k, v]) => `<tr><td style="padding:4px 12px 4px 0;color:#666;">${k}</td><td style="padding:4px 0;font-weight:600;">${v}</td></tr>`)
      .join('');

    const html = `<!DOCTYPE html>
<html lang="nl">
<head><meta charset="UTF-8"></head>
<body style="font-family:sans-serif;background:#f9f9f9;margin:0;padding:24px;">
  <div style="max-width:560px;margin:0 auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);">
    <div style="background:#1C1917;padding:24px 28px;">
      <div style="color:#E8761A;font-size:20px;font-weight:700;">EarthGND</div>
      <div style="color:#F5EFE6;font-size:13px;margin-top:4px;">${toolLabel} — ${dateStr}</div>
    </div>
    <div style="padding:24px 28px;">
      <p style="margin:0 0 16px;color:#333;">Goedemiddag,</p>
      <p style="margin:0 0 20px;color:#555;line-height:1.6;">
        In de bijlage vindt u het rapport van uw aardingsberekening. Hieronder een samenvatting van de resultaten.
      </p>
      <table style="width:100%;border-collapse:collapse;margin-bottom:20px;">
        ${resultRows}
      </table>
      ${warning ? `<p style="background:#fff3cd;border:1px solid #ffc107;padding:10px 14px;border-radius:4px;font-size:12px;color:#856404;margin-bottom:20px;">⚠ ${warning}</p>` : ''}
      <p style="font-size:12px;color:#888;border-top:1px solid #eee;padding-top:16px;margin:0;">
        Dit rapport is indicatief. Meet altijd ter plaatse conform NEN 3140 / NEN 1010.<br>
        <a href="https://earthgnd.nl" style="color:#E8761A;">earthgnd.nl</a>
      </p>
    </div>
  </div>
</body>
</html>`;

    await resend.emails.send({
      from: process.env.RESEND_FROM_EMAIL ?? 'EarthGND <noreply@earthgnd.nl>',
      to: user.email,
      subject,
      html,
      attachments: [
        {
          filename: `earthgnd-${tool}-rapport.pdf`,
          content: pdfBuffer,
        },
      ],
    });

    return NextResponse.json({ success: true });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
